// Generated by gir (https://github.com/gtk-rs/gir @ 1bef39f)
// from gir-files (https://github.com/selaux/gir-files.git @ ec4c204)
// DO NOT EDIT

use bitflags::bitflags;
use glib::translate::*;
use glib::value::FromValue;
use glib::value::ToValue;
use glib::StaticType;
use glib::Type;
use std::fmt;

bitflags! {
    #[doc(alias = "RsvgHandleFlags")]
    pub struct HandleFlags: u32 {
        #[doc(alias = "RSVG_HANDLE_FLAGS_NONE")]
        const FLAGS_NONE = ffi::RSVG_HANDLE_FLAGS_NONE as u32;
        #[doc(alias = "RSVG_HANDLE_FLAG_UNLIMITED")]
        const FLAG_UNLIMITED = ffi::RSVG_HANDLE_FLAG_UNLIMITED as u32;
        #[doc(alias = "RSVG_HANDLE_FLAG_KEEP_IMAGE_DATA")]
        const FLAG_KEEP_IMAGE_DATA = ffi::RSVG_HANDLE_FLAG_KEEP_IMAGE_DATA as u32;
    }
}

impl fmt::Display for HandleFlags {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        <Self as fmt::Debug>::fmt(self, f)
    }
}

#[doc(hidden)]
impl IntoGlib for HandleFlags {
    type GlibType = ffi::RsvgHandleFlags;

    fn into_glib(self) -> ffi::RsvgHandleFlags {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::RsvgHandleFlags> for HandleFlags {
    unsafe fn from_glib(value: ffi::RsvgHandleFlags) -> Self {
        Self::from_bits_truncate(value)
    }
}

impl StaticType for HandleFlags {
    fn static_type() -> Type {
        unsafe { from_glib(ffi::rsvg_handle_flags_get_type()) }
    }
}

impl glib::value::ValueType for HandleFlags {
    type Type = Self;
}

unsafe impl<'a> FromValue<'a> for HandleFlags {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    unsafe fn from_value(value: &'a glib::Value) -> Self {
        from_glib(glib::gobject_ffi::g_value_get_flags(value.to_glib_none().0))
    }
}

impl ToValue for HandleFlags {
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_flags(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}
