// Generated by gir (https://github.com/gtk-rs/gir @ 1bef39f)
// from gir-files (https://github.com/selaux/gir-files.git @ ec4c204)
// DO NOT EDIT

use crate::DimensionData;
use crate::HandleFlags;
use crate::PositionData;
use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use glib::StaticType;
use glib::ToValue;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;
use std::ptr;

glib::wrapper! {
    #[doc(alias = "RsvgHandle")]
    pub struct Handle(Object<ffi::RsvgHandle, ffi::RsvgHandleClass>);

    match fn {
        type_ => || ffi::rsvg_handle_get_type(),
    }
}

impl Handle {
    #[doc(alias = "rsvg_handle_new")]
    pub fn new() -> Handle {
        unsafe {
            from_glib_full(ffi::rsvg_handle_new())
        }
    }

    #[doc(alias = "rsvg_handle_new_from_data")]
    #[doc(alias = "new_from_data")]
    pub fn from_data(data: &[u8]) -> Result<Handle, glib::Error> {
        let data_len = data.len() as usize;
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::rsvg_handle_new_from_data(data.to_glib_none().0, data_len, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "rsvg_handle_new_from_file")]
    #[doc(alias = "new_from_file")]
    pub fn from_file(file_name: &str) -> Result<Handle, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::rsvg_handle_new_from_file(file_name.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    //#[doc(alias = "rsvg_handle_new_from_gfile_sync")]
    //#[doc(alias = "new_from_gfile_sync")]
    //pub fn from_gfile_sync(file: /*Ignored*/&gio::File, flags: HandleFlags, cancellable: /*Ignored*/Option<&gio::Cancellable>) -> Result<Handle, glib::Error> {
    //    unsafe { TODO: call ffi:rsvg_handle_new_from_gfile_sync() }
    //}

    //#[doc(alias = "rsvg_handle_new_from_stream_sync")]
    //#[doc(alias = "new_from_stream_sync")]
    //pub fn from_stream_sync(input_stream: /*Ignored*/&gio::InputStream, base_file: /*Ignored*/Option<&gio::File>, flags: HandleFlags, cancellable: /*Ignored*/Option<&gio::Cancellable>) -> Result<Handle, glib::Error> {
    //    unsafe { TODO: call ffi:rsvg_handle_new_from_stream_sync() }
    //}

    #[doc(alias = "rsvg_handle_new_with_flags")]
    #[doc(alias = "new_with_flags")]
    pub fn with_flags(flags: HandleFlags) -> Handle {
        unsafe {
            from_glib_full(ffi::rsvg_handle_new_with_flags(flags.into_glib()))
        }
    }
}

impl Default for Handle {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_HANDLE: Option<&Handle> = None;

pub trait HandleExt: 'static {
    #[doc(alias = "rsvg_handle_close")]
    fn close(&self) -> Result<(), glib::Error>;

    #[doc(alias = "rsvg_handle_get_dimensions")]
    #[doc(alias = "get_dimensions")]
    fn dimensions(&self) -> DimensionData;

    #[doc(alias = "rsvg_handle_get_dimensions_sub")]
    #[doc(alias = "get_dimensions_sub")]
    fn dimensions_sub(&self, id: Option<&str>) -> Option<DimensionData>;

    #[doc(alias = "rsvg_handle_get_pixbuf")]
    #[doc(alias = "get_pixbuf")]
    fn pixbuf(&self) -> Option<gdk_pixbuf::Pixbuf>;

    #[doc(alias = "rsvg_handle_get_pixbuf_sub")]
    #[doc(alias = "get_pixbuf_sub")]
    fn pixbuf_sub(&self, id: Option<&str>) -> Option<gdk_pixbuf::Pixbuf>;

    #[doc(alias = "rsvg_handle_get_position_sub")]
    #[doc(alias = "get_position_sub")]
    fn position_sub(&self, id: &str) -> Option<PositionData>;

    #[doc(alias = "rsvg_handle_has_sub")]
    fn has_sub(&self, id: &str) -> bool;

    //#[doc(alias = "rsvg_handle_read_stream_sync")]
    //fn read_stream_sync(&self, stream: /*Ignored*/&gio::InputStream, cancellable: /*Ignored*/Option<&gio::Cancellable>) -> Result<(), glib::Error>;

    #[doc(alias = "rsvg_handle_render_cairo")]
    fn render_cairo(&self, cr: &cairo::Context) -> bool;

    #[doc(alias = "rsvg_handle_render_cairo_sub")]
    fn render_cairo_sub(&self, cr: &cairo::Context, id: Option<&str>) -> bool;

    //#[doc(alias = "rsvg_handle_set_base_gfile")]
    //fn set_base_gfile(&self, base_file: /*Ignored*/&gio::File);

    #[doc(alias = "rsvg_handle_set_base_uri")]
    fn set_base_uri(&self, base_uri: &str);

    #[doc(alias = "rsvg_handle_set_dpi")]
    fn set_dpi(&self, dpi: f64);

    #[doc(alias = "rsvg_handle_set_dpi_x_y")]
    fn set_dpi_x_y(&self, dpi_x: f64, dpi_y: f64);

    #[doc(alias = "rsvg_handle_write")]
    fn write(&self, buf: &[u8]) -> Result<(), glib::Error>;

    #[doc(alias = "dpi-x")]
    fn dpi_x(&self) -> f64;

    #[doc(alias = "dpi-x")]
    fn set_dpi_x(&self, dpi_x: f64);

    #[doc(alias = "dpi-y")]
    fn dpi_y(&self) -> f64;

    #[doc(alias = "dpi-y")]
    fn set_dpi_y(&self, dpi_y: f64);

    fn em(&self) -> f64;

    fn ex(&self) -> f64;

    fn flags(&self) -> HandleFlags;

    fn height(&self) -> i32;

    fn width(&self) -> i32;

    #[doc(alias = "dpi-x")]
    fn connect_dpi_x_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "dpi-y")]
    fn connect_dpi_y_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "em")]
    fn connect_em_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "ex")]
    fn connect_ex_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "height")]
    fn connect_height_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "width")]
    fn connect_width_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<Handle>> HandleExt for O {
    fn close(&self) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::rsvg_handle_close(self.as_ref().to_glib_none().0, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn dimensions(&self) -> DimensionData {
        unsafe {
            let mut dimension_data = DimensionData::uninitialized();
            ffi::rsvg_handle_get_dimensions(self.as_ref().to_glib_none().0, dimension_data.to_glib_none_mut().0);
            dimension_data
        }
    }

    fn dimensions_sub(&self, id: Option<&str>) -> Option<DimensionData> {
        unsafe {
            let mut dimension_data = DimensionData::uninitialized();
            let ret = from_glib(ffi::rsvg_handle_get_dimensions_sub(self.as_ref().to_glib_none().0, dimension_data.to_glib_none_mut().0, id.to_glib_none().0));
            if ret { Some(dimension_data) } else { None }
        }
    }

    fn pixbuf(&self) -> Option<gdk_pixbuf::Pixbuf> {
        unsafe {
            from_glib_full(ffi::rsvg_handle_get_pixbuf(self.as_ref().to_glib_none().0))
        }
    }

    fn pixbuf_sub(&self, id: Option<&str>) -> Option<gdk_pixbuf::Pixbuf> {
        unsafe {
            from_glib_full(ffi::rsvg_handle_get_pixbuf_sub(self.as_ref().to_glib_none().0, id.to_glib_none().0))
        }
    }

    fn position_sub(&self, id: &str) -> Option<PositionData> {
        unsafe {
            let mut position_data = PositionData::uninitialized();
            let ret = from_glib(ffi::rsvg_handle_get_position_sub(self.as_ref().to_glib_none().0, position_data.to_glib_none_mut().0, id.to_glib_none().0));
            if ret { Some(position_data) } else { None }
        }
    }

    fn has_sub(&self, id: &str) -> bool {
        unsafe {
            from_glib(ffi::rsvg_handle_has_sub(self.as_ref().to_glib_none().0, id.to_glib_none().0))
        }
    }

    //fn read_stream_sync(&self, stream: /*Ignored*/&gio::InputStream, cancellable: /*Ignored*/Option<&gio::Cancellable>) -> Result<(), glib::Error> {
    //    unsafe { TODO: call ffi:rsvg_handle_read_stream_sync() }
    //}

    fn render_cairo(&self, cr: &cairo::Context) -> bool {
        unsafe {
            from_glib(ffi::rsvg_handle_render_cairo(self.as_ref().to_glib_none().0, mut_override(cr.to_glib_none().0)))
        }
    }

    fn render_cairo_sub(&self, cr: &cairo::Context, id: Option<&str>) -> bool {
        unsafe {
            from_glib(ffi::rsvg_handle_render_cairo_sub(self.as_ref().to_glib_none().0, mut_override(cr.to_glib_none().0), id.to_glib_none().0))
        }
    }

    //fn set_base_gfile(&self, base_file: /*Ignored*/&gio::File) {
    //    unsafe { TODO: call ffi:rsvg_handle_set_base_gfile() }
    //}

    fn set_base_uri(&self, base_uri: &str) {
        unsafe {
            ffi::rsvg_handle_set_base_uri(self.as_ref().to_glib_none().0, base_uri.to_glib_none().0);
        }
    }

    fn set_dpi(&self, dpi: f64) {
        unsafe {
            ffi::rsvg_handle_set_dpi(self.as_ref().to_glib_none().0, dpi);
        }
    }

    fn set_dpi_x_y(&self, dpi_x: f64, dpi_y: f64) {
        unsafe {
            ffi::rsvg_handle_set_dpi_x_y(self.as_ref().to_glib_none().0, dpi_x, dpi_y);
        }
    }

    fn write(&self, buf: &[u8]) -> Result<(), glib::Error> {
        let count = buf.len() as usize;
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::rsvg_handle_write(self.as_ref().to_glib_none().0, buf.to_glib_none().0, count, &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    fn dpi_x(&self) -> f64 {
        unsafe {
            let mut value = glib::Value::from_type(<f64 as StaticType>::static_type());
            glib::gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut glib::gobject_ffi::GObject, b"dpi-x\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().expect("Return Value for property `dpi-x` getter")
        }
    }

    fn set_dpi_x(&self, dpi_x: f64) {
        unsafe {
            glib::gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut glib::gobject_ffi::GObject, b"dpi-x\0".as_ptr() as *const _, dpi_x.to_value().to_glib_none().0);
        }
    }

    fn dpi_y(&self) -> f64 {
        unsafe {
            let mut value = glib::Value::from_type(<f64 as StaticType>::static_type());
            glib::gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut glib::gobject_ffi::GObject, b"dpi-y\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().expect("Return Value for property `dpi-y` getter")
        }
    }

    fn set_dpi_y(&self, dpi_y: f64) {
        unsafe {
            glib::gobject_ffi::g_object_set_property(self.to_glib_none().0 as *mut glib::gobject_ffi::GObject, b"dpi-y\0".as_ptr() as *const _, dpi_y.to_value().to_glib_none().0);
        }
    }

    fn em(&self) -> f64 {
        unsafe {
            let mut value = glib::Value::from_type(<f64 as StaticType>::static_type());
            glib::gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut glib::gobject_ffi::GObject, b"em\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().expect("Return Value for property `em` getter")
        }
    }

    fn ex(&self) -> f64 {
        unsafe {
            let mut value = glib::Value::from_type(<f64 as StaticType>::static_type());
            glib::gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut glib::gobject_ffi::GObject, b"ex\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().expect("Return Value for property `ex` getter")
        }
    }

    fn flags(&self) -> HandleFlags {
        unsafe {
            let mut value = glib::Value::from_type(<HandleFlags as StaticType>::static_type());
            glib::gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut glib::gobject_ffi::GObject, b"flags\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().expect("Return Value for property `flags` getter")
        }
    }

    fn height(&self) -> i32 {
        unsafe {
            let mut value = glib::Value::from_type(<i32 as StaticType>::static_type());
            glib::gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut glib::gobject_ffi::GObject, b"height\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().expect("Return Value for property `height` getter")
        }
    }

    fn width(&self) -> i32 {
        unsafe {
            let mut value = glib::Value::from_type(<i32 as StaticType>::static_type());
            glib::gobject_ffi::g_object_get_property(self.to_glib_none().0 as *mut glib::gobject_ffi::GObject, b"width\0".as_ptr() as *const _, value.to_glib_none_mut().0);
            value.get().expect("Return Value for property `width` getter")
        }
    }

    fn connect_dpi_x_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_dpi_x_trampoline<P: IsA<Handle>, F: Fn(&P) + 'static>(this: *mut ffi::RsvgHandle, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Handle::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::dpi-x\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(notify_dpi_x_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_dpi_y_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_dpi_y_trampoline<P: IsA<Handle>, F: Fn(&P) + 'static>(this: *mut ffi::RsvgHandle, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Handle::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::dpi-y\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(notify_dpi_y_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_em_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_em_trampoline<P: IsA<Handle>, F: Fn(&P) + 'static>(this: *mut ffi::RsvgHandle, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Handle::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::em\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(notify_em_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_ex_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_ex_trampoline<P: IsA<Handle>, F: Fn(&P) + 'static>(this: *mut ffi::RsvgHandle, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Handle::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::ex\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(notify_ex_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_height_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_height_trampoline<P: IsA<Handle>, F: Fn(&P) + 'static>(this: *mut ffi::RsvgHandle, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Handle::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::height\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(notify_height_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_width_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_width_trampoline<P: IsA<Handle>, F: Fn(&P) + 'static>(this: *mut ffi::RsvgHandle, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Handle::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::width\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(notify_width_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl fmt::Display for Handle {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Handle")
    }
}
