// This file was generated by gir (https://github.com/gtk-rs/gir @ f5fca82)
// from gir-files (https://github.com/gtk-rs/gir-files @ ec4c204)
// DO NOT EDIT

mod handle;
pub use self::handle::Handle;
pub use self::handle::HandleExt;

mod flags;
pub use self::flags::HandleFlags;

#[doc(hidden)]
pub mod traits {
    pub use super::HandleExt;
}
