// Generated by gir (https://github.com/gtk-rs/gir @ 1bef39f)
// from gir-files (https://github.com/selaux/gir-files.git @ ec4c204)
// DO NOT EDIT

mod handle;
pub use self::handle::{Handle, HandleExt, NONE_HANDLE};

mod flags;
pub use self::flags::HandleFlags;
