// Generated by gir (https://github.com/gtk-rs/gir @ 1bef39f)
// from gir-files (https://github.com/selaux/gir-files.git @ ec4c204)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT(LIBRSVG_MAJOR_VERSION);
    PRINT_CONSTANT(LIBRSVG_MICRO_VERSION);
    PRINT_CONSTANT(LIBRSVG_MINOR_VERSION);
    PRINT_CONSTANT(LIBRSVG_VERSION);
    PRINT_CONSTANT((gint) RSVG_ERROR_FAILED);
    PRINT_CONSTANT((guint) RSVG_HANDLE_FLAGS_NONE);
    PRINT_CONSTANT((guint) RSVG_HANDLE_FLAG_KEEP_IMAGE_DATA);
    PRINT_CONSTANT((guint) RSVG_HANDLE_FLAG_UNLIMITED);
    return 0;
}
